
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fnaffrights.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.fnaffrights.block.YellowBearTorsoBlock;
import net.mcreator.fnaffrights.block.YellowBearRightLegBlock;
import net.mcreator.fnaffrights.block.YellowBearRightArmBlock;
import net.mcreator.fnaffrights.block.YellowBearLeftLegBlock;
import net.mcreator.fnaffrights.block.YellowBearLeftArmBlock;
import net.mcreator.fnaffrights.block.YellowBearHeadBlock;
import net.mcreator.fnaffrights.block.WitheredGoldenFreddyTorsoBlock;
import net.mcreator.fnaffrights.block.WitheredGoldenFreddyRightLegBlock;
import net.mcreator.fnaffrights.block.WitheredGoldenFreddyRightArmBlock;
import net.mcreator.fnaffrights.block.WitheredGoldenFreddyLeftLegBlock;
import net.mcreator.fnaffrights.block.WitheredGoldenFreddyLeftArmBlock;
import net.mcreator.fnaffrights.block.WitheredGoldenFreddyHeadBlock;
import net.mcreator.fnaffrights.block.WitheredGoldenFreddyBlcokBlock;
import net.mcreator.fnaffrights.block.WitheredFreddyTorsoBlock;
import net.mcreator.fnaffrights.block.WitheredFreddyRightLegBlock;
import net.mcreator.fnaffrights.block.WitheredFreddyRightArmBlock;
import net.mcreator.fnaffrights.block.WitheredFreddyLeftLegBlock;
import net.mcreator.fnaffrights.block.WitheredFreddyLeftArmBlock;
import net.mcreator.fnaffrights.block.WitheredFreddyHeadBlock;
import net.mcreator.fnaffrights.block.WitheredFreddyBlockBlock;
import net.mcreator.fnaffrights.block.WitheredFoxyTorsoBlock;
import net.mcreator.fnaffrights.block.WitheredFoxyRightArmBlock;
import net.mcreator.fnaffrights.block.WitheredFoxyLegBlock;
import net.mcreator.fnaffrights.block.WitheredFoxyLeftLegBlock;
import net.mcreator.fnaffrights.block.WitheredFoxyLeftArmBlock;
import net.mcreator.fnaffrights.block.WitheredFoxyHeadBlock;
import net.mcreator.fnaffrights.block.WitheredFoxyBlockBlock;
import net.mcreator.fnaffrights.block.WitheredChicaTorsoBlock;
import net.mcreator.fnaffrights.block.WitheredChicaRightLegBlock;
import net.mcreator.fnaffrights.block.WitheredChicaRightArmBlock;
import net.mcreator.fnaffrights.block.WitheredChicaLeftLegBlock;
import net.mcreator.fnaffrights.block.WitheredChicaLeftArmBlock;
import net.mcreator.fnaffrights.block.WitheredChicaHeadBlock;
import net.mcreator.fnaffrights.block.WitheredChicaBlockBlock;
import net.mcreator.fnaffrights.block.WitheredBonnieTorsoBlock;
import net.mcreator.fnaffrights.block.WitheredBonnieRightLegBlock;
import net.mcreator.fnaffrights.block.WitheredBonnieRightArmBlock;
import net.mcreator.fnaffrights.block.WitheredBonnieLeftLegBlock;
import net.mcreator.fnaffrights.block.WitheredBonnieHeadBlock;
import net.mcreator.fnaffrights.block.WitheredBonnieBlockBlock;
import net.mcreator.fnaffrights.block.VasstronicBlock;
import net.mcreator.fnaffrights.block.VassilisBlock;
import net.mcreator.fnaffrights.block.VassilisABlock;
import net.mcreator.fnaffrights.block.UnBonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.UnBonnieShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.ToyFreddyTorsoBlock;
import net.mcreator.fnaffrights.block.ToyFreddyShowtimeBlock;
import net.mcreator.fnaffrights.block.ToyFreddyShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.ToyFreddyRightLegBlock;
import net.mcreator.fnaffrights.block.ToyFreddyRightArmBlock;
import net.mcreator.fnaffrights.block.ToyFreddyLeftLegBlock;
import net.mcreator.fnaffrights.block.ToyFreddyLeftArmBlock;
import net.mcreator.fnaffrights.block.ToyFreddyHeadBlock;
import net.mcreator.fnaffrights.block.ToyFreddyBlockBlock;
import net.mcreator.fnaffrights.block.ToyFoxyTorsoBlock;
import net.mcreator.fnaffrights.block.ToyFoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.ToyFoxyShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.ToyFoxyRightLegBlock;
import net.mcreator.fnaffrights.block.ToyFoxyRightArmBlock;
import net.mcreator.fnaffrights.block.ToyFoxyLeftLegBlock;
import net.mcreator.fnaffrights.block.ToyFoxyLeftArmBlock;
import net.mcreator.fnaffrights.block.ToyFoxyHeadBlock;
import net.mcreator.fnaffrights.block.ToyFoxyBlockBlock;
import net.mcreator.fnaffrights.block.ToyChicaTorsoBlock;
import net.mcreator.fnaffrights.block.ToyChicaShowtimeBlock;
import net.mcreator.fnaffrights.block.ToyChicaShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.ToyChicaRightLegBlock;
import net.mcreator.fnaffrights.block.ToyChicaRightArmBlock;
import net.mcreator.fnaffrights.block.ToyChicaLeftLegBlock;
import net.mcreator.fnaffrights.block.ToyChicaLeftArmBlock;
import net.mcreator.fnaffrights.block.ToyChicaHeadBlock;
import net.mcreator.fnaffrights.block.ToyChicaBlockBlock;
import net.mcreator.fnaffrights.block.ToyCarnieShowtimeBlock;
import net.mcreator.fnaffrights.block.ToyCarnieActiveBlock;
import net.mcreator.fnaffrights.block.ToyBonnieTorsoBlock;
import net.mcreator.fnaffrights.block.ToyBonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.ToyBonnieShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.ToyBonnieRightLegBlock;
import net.mcreator.fnaffrights.block.ToyBonnieRightArmBlock;
import net.mcreator.fnaffrights.block.ToyBonnieLeftLegBlock;
import net.mcreator.fnaffrights.block.ToyBonnieLeftArmBlock;
import net.mcreator.fnaffrights.block.ToyBonnieHeadBlock;
import net.mcreator.fnaffrights.block.ToyBonnieBlockBlock;
import net.mcreator.fnaffrights.block.SpringtrapShowtimeBlock;
import net.mcreator.fnaffrights.block.SpringtrapShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.SpringbonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.SpringBonnieTorsoBlock;
import net.mcreator.fnaffrights.block.SpringBonnieShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.SpringBonnieRightLegBlock;
import net.mcreator.fnaffrights.block.SpringBonnieRightArmBlock;
import net.mcreator.fnaffrights.block.SpringBonnieLeftLEgBlock;
import net.mcreator.fnaffrights.block.SpringBonnieLeftArmBlock;
import net.mcreator.fnaffrights.block.SpringBonnieHeadBlock;
import net.mcreator.fnaffrights.block.SpringBonnieBunnieTorsoBlock;
import net.mcreator.fnaffrights.block.SpringBonnieBunnieShowtimeBlock;
import net.mcreator.fnaffrights.block.SpringBonnieBunnieShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.SpringBonnieBunnieRightLegBlock;
import net.mcreator.fnaffrights.block.SpringBonnieBunnieRightArmBlock;
import net.mcreator.fnaffrights.block.SpringBonnieBunnieLeftLegBlock;
import net.mcreator.fnaffrights.block.SpringBonnieBunnieLeftArmBlock;
import net.mcreator.fnaffrights.block.SpringBonnieBunnieHeadBlock;
import net.mcreator.fnaffrights.block.PuppetwalldecorBlock;
import net.mcreator.fnaffrights.block.PuppetInTheBoxBlockBlock;
import net.mcreator.fnaffrights.block.PuppetBoxWindingBlock;
import net.mcreator.fnaffrights.block.PuppetBoxSlumpedBlock;
import net.mcreator.fnaffrights.block.PuppetBoxJumpscareBlock;
import net.mcreator.fnaffrights.block.PuppetBoxGiftBlock;
import net.mcreator.fnaffrights.block.OffsetToyFreddyShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetToyFreddyActiveBlock;
import net.mcreator.fnaffrights.block.OffsetToyFoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetToyFoxyActiveBlock;
import net.mcreator.fnaffrights.block.OffsetSpringBonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetSpringBonnieActiveBlock;
import net.mcreator.fnaffrights.block.OffsetFreddyShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetFreddyFazbearShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetFreddyFazbearActiveBlock;
import net.mcreator.fnaffrights.block.OffsetFreddyActiveBlock;
import net.mcreator.fnaffrights.block.OffsetFredBearShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetFredBearActiveBlock;
import net.mcreator.fnaffrights.block.OffsetFoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetFoxyPirateShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetFoxyPirateActiveBlock;
import net.mcreator.fnaffrights.block.OffsetFoxyActiveBlock;
import net.mcreator.fnaffrights.block.OffsetFixedFoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.OffsetFixedFoxyActiveBlock;
import net.mcreator.fnaffrights.block.GoldenFreddyShowtimeBlock;
import net.mcreator.fnaffrights.block.GoldenFreddyShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.GlitchtrapShowtimeBlock;
import net.mcreator.fnaffrights.block.GlitchtrapShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.GlitchBonnieTorsoBlock;
import net.mcreator.fnaffrights.block.GlitchBonnieHeadBlock;
import net.mcreator.fnaffrights.block.GeneratorBlock;
import net.mcreator.fnaffrights.block.Generator8Block;
import net.mcreator.fnaffrights.block.Generator7Block;
import net.mcreator.fnaffrights.block.Generator6Block;
import net.mcreator.fnaffrights.block.Generator5Block;
import net.mcreator.fnaffrights.block.Generator4Block;
import net.mcreator.fnaffrights.block.Generator3Block;
import net.mcreator.fnaffrights.block.Generator2Block;
import net.mcreator.fnaffrights.block.Generator1Block;
import net.mcreator.fnaffrights.block.FreddyTorsoBlock;
import net.mcreator.fnaffrights.block.FreddyShowtimeBlock;
import net.mcreator.fnaffrights.block.FreddyShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.FreddyRightLegBlock;
import net.mcreator.fnaffrights.block.FreddyRightArmBlock;
import net.mcreator.fnaffrights.block.FreddyLeftLegBlock;
import net.mcreator.fnaffrights.block.FreddyLeftArmBlock;
import net.mcreator.fnaffrights.block.FreddyHeadBlock;
import net.mcreator.fnaffrights.block.FreddyFazbearheadBlock;
import net.mcreator.fnaffrights.block.FreddyFazbeareftLegBlock;
import net.mcreator.fnaffrights.block.FreddyFazbearTorsoBlock;
import net.mcreator.fnaffrights.block.FreddyFazbearShowtimeBlock;
import net.mcreator.fnaffrights.block.FreddyFazbearShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.FreddyFazbearRightLegBlock;
import net.mcreator.fnaffrights.block.FreddyFazbearRightArmBlock;
import net.mcreator.fnaffrights.block.FreddyFazbearLeftArmBlock;
import net.mcreator.fnaffrights.block.FreddyBoxSpinBlock;
import net.mcreator.fnaffrights.block.FreddyBoxBlock;
import net.mcreator.fnaffrights.block.FreddyBoxActiveBlock;
import net.mcreator.fnaffrights.block.FreddyBlockBlock;
import net.mcreator.fnaffrights.block.FredbearShowtimeBlock;
import net.mcreator.fnaffrights.block.FredbearShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.FredBearTorsoBlock;
import net.mcreator.fnaffrights.block.FredBearRightLegBlock;
import net.mcreator.fnaffrights.block.FredBearRightArmBlock;
import net.mcreator.fnaffrights.block.FredBearLeftLegBlock;
import net.mcreator.fnaffrights.block.FredBearLeftArmBlock;
import net.mcreator.fnaffrights.block.FredBearHeadBlock;
import net.mcreator.fnaffrights.block.FoxyTorsoBlock;
import net.mcreator.fnaffrights.block.FoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.FoxyShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.FoxyRightLegBlock;
import net.mcreator.fnaffrights.block.FoxyRightArmBlock;
import net.mcreator.fnaffrights.block.FoxyPirateTorsoBlock;
import net.mcreator.fnaffrights.block.FoxyPirateShowtimeBlock;
import net.mcreator.fnaffrights.block.FoxyPirateShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.FoxyPirateRightLegBlock;
import net.mcreator.fnaffrights.block.FoxyPirateRightArmBlock;
import net.mcreator.fnaffrights.block.FoxyPirateLeftLegBlock;
import net.mcreator.fnaffrights.block.FoxyPirateLeftArmBlock;
import net.mcreator.fnaffrights.block.FoxyPirateHeadBlock;
import net.mcreator.fnaffrights.block.FoxyLegBlock;
import net.mcreator.fnaffrights.block.FoxyLeftArmBlock;
import net.mcreator.fnaffrights.block.FoxyHeadBlock;
import net.mcreator.fnaffrights.block.FoxyBlockBlock;
import net.mcreator.fnaffrights.block.FixedFoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.FixedFoxyShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.FazbearLogoBlock;
import net.mcreator.fnaffrights.block.FazbearLogo2Block;
import net.mcreator.fnaffrights.block.FazbearCrateBlockBlock;
import net.mcreator.fnaffrights.block.Enod02BonnieHeadBlock;
import net.mcreator.fnaffrights.block.Endo02TorsoBlock;
import net.mcreator.fnaffrights.block.Endo02RightLegBlock;
import net.mcreator.fnaffrights.block.Endo02RightArmBlock;
import net.mcreator.fnaffrights.block.Endo02LeftLegBlock;
import net.mcreator.fnaffrights.block.Endo02LeftArmBlock;
import net.mcreator.fnaffrights.block.Endo02HeadBlock;
import net.mcreator.fnaffrights.block.Endo02FoxyHeadBlock;
import net.mcreator.fnaffrights.block.Endo02ChicaHeadBlock;
import net.mcreator.fnaffrights.block.Endo02BlockBlock;
import net.mcreator.fnaffrights.block.Endo01TorsoBlock;
import net.mcreator.fnaffrights.block.Endo01RightLegBlock;
import net.mcreator.fnaffrights.block.Endo01RightArmBlock;
import net.mcreator.fnaffrights.block.Endo01LeftLegBlock;
import net.mcreator.fnaffrights.block.Endo01LeftArmBlock;
import net.mcreator.fnaffrights.block.Endo01HeadBlock;
import net.mcreator.fnaffrights.block.EmptyboxBlock;
import net.mcreator.fnaffrights.block.ClassicChicaShowtimeBlock;
import net.mcreator.fnaffrights.block.ClassicChicaShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.ChristmasFreddyBlock;
import net.mcreator.fnaffrights.block.ChristmasFreddyABlock;
import net.mcreator.fnaffrights.block.ChristmasFoxyBlock;
import net.mcreator.fnaffrights.block.ChristmasFoxyABlock;
import net.mcreator.fnaffrights.block.ChristmasChicaBlock;
import net.mcreator.fnaffrights.block.ChristmasChicaABlock;
import net.mcreator.fnaffrights.block.ChristmasBonnieBlock;
import net.mcreator.fnaffrights.block.ChristmasBonnieABlock;
import net.mcreator.fnaffrights.block.ChicaTorsoBlock;
import net.mcreator.fnaffrights.block.ChicaShowtimeBlock;
import net.mcreator.fnaffrights.block.ChicaShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.ChicaRightLegBlock;
import net.mcreator.fnaffrights.block.ChicaRightArmBlock;
import net.mcreator.fnaffrights.block.ChicaLeftLegBlock;
import net.mcreator.fnaffrights.block.ChicaLeftArmBlock;
import net.mcreator.fnaffrights.block.ChicaHeadBlock;
import net.mcreator.fnaffrights.block.ChicaChickenTorsoBlock;
import net.mcreator.fnaffrights.block.ChicaChickenRightLegBlock;
import net.mcreator.fnaffrights.block.ChicaChickenRightArmBlock;
import net.mcreator.fnaffrights.block.ChicaChickenLeftLegBlock;
import net.mcreator.fnaffrights.block.ChicaChickenLeftArmBlock;
import net.mcreator.fnaffrights.block.ChicaChickenHeadBlock;
import net.mcreator.fnaffrights.block.ChicaBlockBlock;
import net.mcreator.fnaffrights.block.CaptainFoxyStatueBlock;
import net.mcreator.fnaffrights.block.BurntToyFreddyJumpscareBlock;
import net.mcreator.fnaffrights.block.BurntToyChicaBlock;
import net.mcreator.fnaffrights.block.BurntToyBonnieJumpscareBlock;
import net.mcreator.fnaffrights.block.BrokenFoxyPirateTorsoBlock;
import net.mcreator.fnaffrights.block.BrokenFoxyPirateRightLegBlock;
import net.mcreator.fnaffrights.block.BrokenFoxyPirateRightArmBlock;
import net.mcreator.fnaffrights.block.BrokenFoxyPirateLeftLegBlock;
import net.mcreator.fnaffrights.block.BrokenFoxyPirateLeftArmBlock;
import net.mcreator.fnaffrights.block.BrokenFoxyPirateHeadBlock;
import net.mcreator.fnaffrights.block.BonnieTorsoBlock;
import net.mcreator.fnaffrights.block.BonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.BonnieShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.BonnieRightLegBlock;
import net.mcreator.fnaffrights.block.BonnieRightArmBlock;
import net.mcreator.fnaffrights.block.BonnieMaskBlockBlock;
import net.mcreator.fnaffrights.block.BonnieLeftLegBlock;
import net.mcreator.fnaffrights.block.BonnieLeftArmBlock;
import net.mcreator.fnaffrights.block.BonnieHeadBlock;
import net.mcreator.fnaffrights.block.BonnieBunnieTorsoBlock;
import net.mcreator.fnaffrights.block.BonnieBunnieShowtimeBlock;
import net.mcreator.fnaffrights.block.BonnieBunnieShowtimeActiveBlock;
import net.mcreator.fnaffrights.block.BonnieBunnieRightLegBlock;
import net.mcreator.fnaffrights.block.BonnieBunnieRightArmBlock;
import net.mcreator.fnaffrights.block.BonnieBunnieLeftLegBlock;
import net.mcreator.fnaffrights.block.BonnieBunnieLeftArmBlock;
import net.mcreator.fnaffrights.block.BonnieBunnieHeadBlock;
import net.mcreator.fnaffrights.block.BonnieBlockBlock;
import net.mcreator.fnaffrights.block.BlloonBoyStatueBlock;
import net.mcreator.fnaffrights.block.AngledToyCarnieBlock;
import net.mcreator.fnaffrights.block.AngledBlloonBoyStatueBlock;
import net.mcreator.fnaffrights.block.AYellowBearShowtimeBlock;
import net.mcreator.fnaffrights.block.AYellowBearActiveBlock;
import net.mcreator.fnaffrights.block.AToyFreddyShowtimeBlock;
import net.mcreator.fnaffrights.block.AToyFreddyActiveBlock;
import net.mcreator.fnaffrights.block.AToyFoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.AToyFoxyActiveBlock;
import net.mcreator.fnaffrights.block.AToyChicaShowtimeBlock;
import net.mcreator.fnaffrights.block.AToyChicaActiveBlock;
import net.mcreator.fnaffrights.block.AToyBonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.AToyBonnieActiveBlock;
import net.mcreator.fnaffrights.block.ASpringtrapShowtimeBlock;
import net.mcreator.fnaffrights.block.ASpringtrapActiveBlock;
import net.mcreator.fnaffrights.block.ASpringBonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.ASpringBonnieBunnieShowtimeBlock;
import net.mcreator.fnaffrights.block.ASpringBonnieBunnieActiveBlock;
import net.mcreator.fnaffrights.block.ASpringBonnieActiveBlock;
import net.mcreator.fnaffrights.block.AShavenBonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.AShavenBonnieActiveBlock;
import net.mcreator.fnaffrights.block.AGltichBonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.AGlitchBonnieActiveBlock;
import net.mcreator.fnaffrights.block.AFreddyShowtimeBlock;
import net.mcreator.fnaffrights.block.AFreddyFazbearShowtimeBlock;
import net.mcreator.fnaffrights.block.AFreddyFazbearActiveBlock;
import net.mcreator.fnaffrights.block.AFreddyActiveBlock;
import net.mcreator.fnaffrights.block.AFredbearShowtimeBlock;
import net.mcreator.fnaffrights.block.AFredbearActiveBlock;
import net.mcreator.fnaffrights.block.AFoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.AFoxyPirateShowtimeBlock;
import net.mcreator.fnaffrights.block.AFoxyPirateActiveBlock;
import net.mcreator.fnaffrights.block.AFoxyActiveBlock;
import net.mcreator.fnaffrights.block.AFixedFoxyShowtimeBlock;
import net.mcreator.fnaffrights.block.AFixedFoxyActiveBlock;
import net.mcreator.fnaffrights.block.AChicaShowtimeBlock;
import net.mcreator.fnaffrights.block.AChicaChickenShowtimeBlock;
import net.mcreator.fnaffrights.block.AChicaChickenActiveBlock;
import net.mcreator.fnaffrights.block.AChicaActiveBlock;
import net.mcreator.fnaffrights.block.ABonnieShowtimeBlock;
import net.mcreator.fnaffrights.block.ABonnieBunnyActiveBlock;
import net.mcreator.fnaffrights.block.ABonnieBunnieShowtimeBlock;
import net.mcreator.fnaffrights.block.ABonnieActiveBlock;
import net.mcreator.fnaffrights.FnafFrightsMod;

public class FnafFrightsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FnafFrightsMod.MODID);
	public static final RegistryObject<Block> FOXY_HEAD = REGISTRY.register("foxy_head", () -> new FoxyHeadBlock());
	public static final RegistryObject<Block> FOXY_LEFT_ARM = REGISTRY.register("foxy_left_arm", () -> new FoxyLeftArmBlock());
	public static final RegistryObject<Block> FOXY_TORSO = REGISTRY.register("foxy_torso", () -> new FoxyTorsoBlock());
	public static final RegistryObject<Block> FOXY_RIGHT_ARM = REGISTRY.register("foxy_right_arm", () -> new FoxyRightArmBlock());
	public static final RegistryObject<Block> FOXY_LEG = REGISTRY.register("foxy_leg", () -> new FoxyLegBlock());
	public static final RegistryObject<Block> FOXY_RIGHT_LEG = REGISTRY.register("foxy_right_leg", () -> new FoxyRightLegBlock());
	public static final RegistryObject<Block> WITHERED_FOXY_HEAD = REGISTRY.register("withered_foxy_head", () -> new WitheredFoxyHeadBlock());
	public static final RegistryObject<Block> WITHERED_FOXY_TORSO = REGISTRY.register("withered_foxy_torso", () -> new WitheredFoxyTorsoBlock());
	public static final RegistryObject<Block> WITHERED_FOXY_LEFT_LEG = REGISTRY.register("withered_foxy_left_leg", () -> new WitheredFoxyLeftLegBlock());
	public static final RegistryObject<Block> WITHERED_FOXY_LEG = REGISTRY.register("withered_foxy_leg", () -> new WitheredFoxyLegBlock());
	public static final RegistryObject<Block> FREDDY_HEAD = REGISTRY.register("freddy_head", () -> new FreddyHeadBlock());
	public static final RegistryObject<Block> FREDDY_LEFT_ARM = REGISTRY.register("freddy_left_arm", () -> new FreddyLeftArmBlock());
	public static final RegistryObject<Block> FREDDY_TORSO = REGISTRY.register("freddy_torso", () -> new FreddyTorsoBlock());
	public static final RegistryObject<Block> FREDDY_RIGHT_ARM = REGISTRY.register("freddy_right_arm", () -> new FreddyRightArmBlock());
	public static final RegistryObject<Block> FREDDY_LEFT_LEG = REGISTRY.register("freddy_left_leg", () -> new FreddyLeftLegBlock());
	public static final RegistryObject<Block> FREDDY_RIGHT_LEG = REGISTRY.register("freddy_right_leg", () -> new FreddyRightLegBlock());
	public static final RegistryObject<Block> WITHERED_FREDDY_HEAD = REGISTRY.register("withered_freddy_head", () -> new WitheredFreddyHeadBlock());
	public static final RegistryObject<Block> WITHERED_FREDDY_LEFT_ARM = REGISTRY.register("withered_freddy_left_arm", () -> new WitheredFreddyLeftArmBlock());
	public static final RegistryObject<Block> WITHERED_FREDDY_TORSO = REGISTRY.register("withered_freddy_torso", () -> new WitheredFreddyTorsoBlock());
	public static final RegistryObject<Block> WITHERED_FREDDY_RIGHT_ARM = REGISTRY.register("withered_freddy_right_arm", () -> new WitheredFreddyRightArmBlock());
	public static final RegistryObject<Block> WITHERED_FREDDY_LEFT_LEG = REGISTRY.register("withered_freddy_left_leg", () -> new WitheredFreddyLeftLegBlock());
	public static final RegistryObject<Block> WITHERED_FREDDY_RIGHT_LEG = REGISTRY.register("withered_freddy_right_leg", () -> new WitheredFreddyRightLegBlock());
	public static final RegistryObject<Block> WITHERED_GOLDEN_FREDDY_HEAD = REGISTRY.register("withered_golden_freddy_head", () -> new WitheredGoldenFreddyHeadBlock());
	public static final RegistryObject<Block> WITHERED_GOLDEN_FREDDY_LEFT_ARM = REGISTRY.register("withered_golden_freddy_left_arm", () -> new WitheredGoldenFreddyLeftArmBlock());
	public static final RegistryObject<Block> WITHERED_GOLDEN_FREDDY_TORSO = REGISTRY.register("withered_golden_freddy_torso", () -> new WitheredGoldenFreddyTorsoBlock());
	public static final RegistryObject<Block> WITHERED_GOLDEN_FREDDY_RIGHT_ARM = REGISTRY.register("withered_golden_freddy_right_arm", () -> new WitheredGoldenFreddyRightArmBlock());
	public static final RegistryObject<Block> WITHERED_GOLDEN_FREDDY_LEFT_LEG = REGISTRY.register("withered_golden_freddy_left_leg", () -> new WitheredGoldenFreddyLeftLegBlock());
	public static final RegistryObject<Block> WITHERED_GOLDEN_FREDDY_RIGHT_LEG = REGISTRY.register("withered_golden_freddy_right_leg", () -> new WitheredGoldenFreddyRightLegBlock());
	public static final RegistryObject<Block> PUPPET_IN_THE_BOX_BLOCK = REGISTRY.register("puppet_in_the_box_block", () -> new PuppetInTheBoxBlockBlock());
	public static final RegistryObject<Block> WITHERED_FOXY_LEFT_ARM = REGISTRY.register("withered_foxy_left_arm", () -> new WitheredFoxyLeftArmBlock());
	public static final RegistryObject<Block> WITHERED_FOXY_RIGHT_ARM = REGISTRY.register("withered_foxy_right_arm", () -> new WitheredFoxyRightArmBlock());
	public static final RegistryObject<Block> WITHERED_BONNIE_HEAD = REGISTRY.register("withered_bonnie_head", () -> new WitheredBonnieHeadBlock());
	public static final RegistryObject<Block> WITHERED_BONNIE_RIGHT_ARM = REGISTRY.register("withered_bonnie_right_arm", () -> new WitheredBonnieRightArmBlock());
	public static final RegistryObject<Block> WITHERED_BONNIE_TORSO = REGISTRY.register("withered_bonnie_torso", () -> new WitheredBonnieTorsoBlock());
	public static final RegistryObject<Block> WITHERED_BONNIE_LEFT_LEG = REGISTRY.register("withered_bonnie_left_leg", () -> new WitheredBonnieLeftLegBlock());
	public static final RegistryObject<Block> WITHERED_BONNIE_RIGHT_LEG = REGISTRY.register("withered_bonnie_right_leg", () -> new WitheredBonnieRightLegBlock());
	public static final RegistryObject<Block> BONNIE_LEFT_LEG = REGISTRY.register("bonnie_left_leg", () -> new BonnieLeftLegBlock());
	public static final RegistryObject<Block> BONNIE_TORSO = REGISTRY.register("bonnie_torso", () -> new BonnieTorsoBlock());
	public static final RegistryObject<Block> BONNIE_LEFT_ARM = REGISTRY.register("bonnie_left_arm", () -> new BonnieLeftArmBlock());
	public static final RegistryObject<Block> BONNIE_RIGHT_ARM = REGISTRY.register("bonnie_right_arm", () -> new BonnieRightArmBlock());
	public static final RegistryObject<Block> BONNIE_RIGHT_LEG = REGISTRY.register("bonnie_right_leg", () -> new BonnieRightLegBlock());
	public static final RegistryObject<Block> BONNIE_HEAD = REGISTRY.register("bonnie_head", () -> new BonnieHeadBlock());
	public static final RegistryObject<Block> BONNIE_MASK_BLOCK = REGISTRY.register("bonnie_mask_block", () -> new BonnieMaskBlockBlock());
	public static final RegistryObject<Block> WITHERED_CHICA_RIGHT_ARM = REGISTRY.register("withered_chica_right_arm", () -> new WitheredChicaRightArmBlock());
	public static final RegistryObject<Block> WITHERED_CHICA_RIGHT_LEG = REGISTRY.register("withered_chica_right_leg", () -> new WitheredChicaRightLegBlock());
	public static final RegistryObject<Block> WITHERED_CHICA_HEAD = REGISTRY.register("withered_chica_head", () -> new WitheredChicaHeadBlock());
	public static final RegistryObject<Block> WITHERED_CHICA_LEFT_LEG = REGISTRY.register("withered_chica_left_leg", () -> new WitheredChicaLeftLegBlock());
	public static final RegistryObject<Block> WITHERED_CHICA_TORSO = REGISTRY.register("withered_chica_torso", () -> new WitheredChicaTorsoBlock());
	public static final RegistryObject<Block> WITHERED_CHICA_LEFT_ARM = REGISTRY.register("withered_chica_left_arm", () -> new WitheredChicaLeftArmBlock());
	public static final RegistryObject<Block> CHICA_RIGHT_ARM = REGISTRY.register("chica_right_arm", () -> new ChicaRightArmBlock());
	public static final RegistryObject<Block> CHICA_RIGHT_LEG = REGISTRY.register("chica_right_leg", () -> new ChicaRightLegBlock());
	public static final RegistryObject<Block> CHICA_HEAD = REGISTRY.register("chica_head", () -> new ChicaHeadBlock());
	public static final RegistryObject<Block> CHICA_LEFT_ARM = REGISTRY.register("chica_left_arm", () -> new ChicaLeftArmBlock());
	public static final RegistryObject<Block> CHICA_TORSO = REGISTRY.register("chica_torso", () -> new ChicaTorsoBlock());
	public static final RegistryObject<Block> CHICA_LEFT_LEG = REGISTRY.register("chica_left_leg", () -> new ChicaLeftLegBlock());
	public static final RegistryObject<Block> TOY_BONNIE_TORSO = REGISTRY.register("toy_bonnie_torso", () -> new ToyBonnieTorsoBlock());
	public static final RegistryObject<Block> TOY_BONNIE_HEAD = REGISTRY.register("toy_bonnie_head", () -> new ToyBonnieHeadBlock());
	public static final RegistryObject<Block> TOY_BONNIE_RIGHT_ARM = REGISTRY.register("toy_bonnie_right_arm", () -> new ToyBonnieRightArmBlock());
	public static final RegistryObject<Block> TOY_BONNIE_RIGHT_LEG = REGISTRY.register("toy_bonnie_right_leg", () -> new ToyBonnieRightLegBlock());
	public static final RegistryObject<Block> TOY_BONNIE_LEFT_ARM = REGISTRY.register("toy_bonnie_left_arm", () -> new ToyBonnieLeftArmBlock());
	public static final RegistryObject<Block> TOY_BONNIE_LEFT_LEG = REGISTRY.register("toy_bonnie_left_leg", () -> new ToyBonnieLeftLegBlock());
	public static final RegistryObject<Block> TOY_BONNIE_BLOCK = REGISTRY.register("toy_bonnie_block", () -> new ToyBonnieBlockBlock());
	public static final RegistryObject<Block> FAZBEAR_LOGO = REGISTRY.register("fazbear_logo", () -> new FazbearLogoBlock());
	public static final RegistryObject<Block> FREDDY_BOX = REGISTRY.register("freddy_box", () -> new FreddyBoxBlock());
	public static final RegistryObject<Block> FAZBEAR_LOGO_2 = REGISTRY.register("fazbear_logo_2", () -> new FazbearLogo2Block());
	public static final RegistryObject<Block> TOY_FOXY_TORSO = REGISTRY.register("toy_foxy_torso", () -> new ToyFoxyTorsoBlock());
	public static final RegistryObject<Block> TOY_FOXY_HEAD = REGISTRY.register("toy_foxy_head", () -> new ToyFoxyHeadBlock());
	public static final RegistryObject<Block> TOY_FOXY_RIGHT_ARM = REGISTRY.register("toy_foxy_right_arm", () -> new ToyFoxyRightArmBlock());
	public static final RegistryObject<Block> TOY_FOXY_RIGHT_LEG = REGISTRY.register("toy_foxy_right_leg", () -> new ToyFoxyRightLegBlock());
	public static final RegistryObject<Block> TOY_FOXY_LEFT_ARM = REGISTRY.register("toy_foxy_left_arm", () -> new ToyFoxyLeftArmBlock());
	public static final RegistryObject<Block> TOY_FOXY_LEFT_LEG = REGISTRY.register("toy_foxy_left_leg", () -> new ToyFoxyLeftLegBlock());
	public static final RegistryObject<Block> TOY_FOXY_BLOCK = REGISTRY.register("toy_foxy_block", () -> new ToyFoxyBlockBlock());
	public static final RegistryObject<Block> FREDDY_BLOCK = REGISTRY.register("freddy_block", () -> new FreddyBlockBlock());
	public static final RegistryObject<Block> WITHERED_FREDDY_BLOCK = REGISTRY.register("withered_freddy_block", () -> new WitheredFreddyBlockBlock());
	public static final RegistryObject<Block> WITHERED_GOLDEN_FREDDY_BLOCK = REGISTRY.register("withered_golden_freddy_block", () -> new WitheredGoldenFreddyBlcokBlock());
	public static final RegistryObject<Block> TOY_BONNIE_SHOWTIME = REGISTRY.register("toy_bonnie_showtime", () -> new ToyBonnieShowtimeBlock());
	public static final RegistryObject<Block> TOY_BONNIE_SHOWTIME_ACTIVE = REGISTRY.register("toy_bonnie_showtime_active", () -> new ToyBonnieShowtimeActiveBlock());
	public static final RegistryObject<Block> TOY_CHICA_SHOWTIME = REGISTRY.register("toy_chica_showtime", () -> new ToyChicaShowtimeBlock());
	public static final RegistryObject<Block> TOY_CHICA_SHOWTIME_ACTIVE = REGISTRY.register("toy_chica_showtime_active", () -> new ToyChicaShowtimeActiveBlock());
	public static final RegistryObject<Block> TOY_FREDDY_SHOWTIME = REGISTRY.register("toy_freddy_showtime", () -> new ToyFreddyShowtimeBlock());
	public static final RegistryObject<Block> TOY_FREDDY_SHOWTIME_ACTIVE = REGISTRY.register("toy_freddy_showtime_active", () -> new ToyFreddyShowtimeActiveBlock());
	public static final RegistryObject<Block> FREDDY_SHOWTIME = REGISTRY.register("freddy_showtime", () -> new FreddyShowtimeBlock());
	public static final RegistryObject<Block> FREDDY_SHOWTIME_ACTIVE = REGISTRY.register("freddy_showtime_active", () -> new FreddyShowtimeActiveBlock());
	public static final RegistryObject<Block> BONNIE_SHOWTIME = REGISTRY.register("bonnie_showtime", () -> new BonnieShowtimeBlock());
	public static final RegistryObject<Block> BONNIE_SHOWTIME_ACTIVE = REGISTRY.register("bonnie_showtime_active", () -> new BonnieShowtimeActiveBlock());
	public static final RegistryObject<Block> CHICA_SHOWTIME = REGISTRY.register("chica_showtime", () -> new ChicaShowtimeBlock());
	public static final RegistryObject<Block> CHICA_SHOWTIME_ACTIVE = REGISTRY.register("chica_showtime_active", () -> new ChicaShowtimeActiveBlock());
	public static final RegistryObject<Block> FOXY_SHOWTIME = REGISTRY.register("foxy_showtime", () -> new FoxyShowtimeBlock());
	public static final RegistryObject<Block> FOXY_SHOWTIME_ACTIVE = REGISTRY.register("foxy_showtime_active", () -> new FoxyShowtimeActiveBlock());
	public static final RegistryObject<Block> TOY_FOXY_SHOWTIME = REGISTRY.register("toy_foxy_showtime", () -> new ToyFoxyShowtimeBlock());
	public static final RegistryObject<Block> TOY_FOXY_SHOWTIME_ACTIVE = REGISTRY.register("toy_foxy_showtime_active", () -> new ToyFoxyShowtimeActiveBlock());
	public static final RegistryObject<Block> TOY_CHICA_BLOCK = REGISTRY.register("toy_chica_block", () -> new ToyChicaBlockBlock());
	public static final RegistryObject<Block> TOY_FREDDY_BLOCK = REGISTRY.register("toy_freddy_block", () -> new ToyFreddyBlockBlock());
	public static final RegistryObject<Block> TOY_FREDDY_TORSO = REGISTRY.register("toy_freddy_torso", () -> new ToyFreddyTorsoBlock());
	public static final RegistryObject<Block> TOY_FREDDY_HEAD = REGISTRY.register("toy_freddy_head", () -> new ToyFreddyHeadBlock());
	public static final RegistryObject<Block> TOY_FREDDY_RIGHT_ARM = REGISTRY.register("toy_freddy_right_arm", () -> new ToyFreddyRightArmBlock());
	public static final RegistryObject<Block> TOY_FREDDY_LEFT_ARM = REGISTRY.register("toy_freddy_left_arm", () -> new ToyFreddyLeftArmBlock());
	public static final RegistryObject<Block> TOY_FREDDY_LEFT_LEG = REGISTRY.register("toy_freddy_left_leg", () -> new ToyFreddyLeftLegBlock());
	public static final RegistryObject<Block> TOY_FREDDY_RIGHT_LEG = REGISTRY.register("toy_freddy_right_leg", () -> new ToyFreddyRightLegBlock());
	public static final RegistryObject<Block> TOY_CHICA_TORSO = REGISTRY.register("toy_chica_torso", () -> new ToyChicaTorsoBlock());
	public static final RegistryObject<Block> TOY_CHICA_RIGHT_ARM = REGISTRY.register("toy_chica_right_arm", () -> new ToyChicaRightArmBlock());
	public static final RegistryObject<Block> TOY_CHICA_HEAD = REGISTRY.register("toy_chica_head", () -> new ToyChicaHeadBlock());
	public static final RegistryObject<Block> TOY_CHICA_LEFT_ARM = REGISTRY.register("toy_chica_left_arm", () -> new ToyChicaLeftArmBlock());
	public static final RegistryObject<Block> TOY_CHICA_LEFT_LEG = REGISTRY.register("toy_chica_left_leg", () -> new ToyChicaLeftLegBlock());
	public static final RegistryObject<Block> TOY_CHICA_RIGHT_LEG = REGISTRY.register("toy_chica_right_leg", () -> new ToyChicaRightLegBlock());
	public static final RegistryObject<Block> FOXY_BLOCK = REGISTRY.register("foxy_block", () -> new FoxyBlockBlock());
	public static final RegistryObject<Block> WITHERED_FOXY_BLOCK = REGISTRY.register("withered_foxy_block", () -> new WitheredFoxyBlockBlock());
	public static final RegistryObject<Block> WITHERED_BONNIE_BLOCK = REGISTRY.register("withered_bonnie_block", () -> new WitheredBonnieBlockBlock());
	public static final RegistryObject<Block> WITHERED_CHICA_BLOCK = REGISTRY.register("withered_chica_block", () -> new WitheredChicaBlockBlock());
	public static final RegistryObject<Block> CHICA_BLOCK = REGISTRY.register("chica_block", () -> new ChicaBlockBlock());
	public static final RegistryObject<Block> BONNIE_BLOCK = REGISTRY.register("bonnie_block", () -> new BonnieBlockBlock());
	public static final RegistryObject<Block> FAZBEAR_CRATE_BLOCK = REGISTRY.register("fazbear_crate_block", () -> new FazbearCrateBlockBlock());
	public static final RegistryObject<Block> SPRINGBONNIE_SHOWTIME = REGISTRY.register("springbonnie_showtime", () -> new SpringbonnieShowtimeBlock());
	public static final RegistryObject<Block> FREDBEAR_SHOWTIME = REGISTRY.register("fredbear_showtime", () -> new FredbearShowtimeBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_SHOWTIME_ACTIVE = REGISTRY.register("spring_bonnie_showtime_active", () -> new SpringBonnieShowtimeActiveBlock());
	public static final RegistryObject<Block> FREDBEAR_SHOWTIME_ACTIVE = REGISTRY.register("fredbear_showtime_active", () -> new FredbearShowtimeActiveBlock());
	public static final RegistryObject<Block> CLASSIC_CHICA_SHOWTIME = REGISTRY.register("classic_chica_showtime", () -> new ClassicChicaShowtimeBlock());
	public static final RegistryObject<Block> CLASSIC_CHICA_SHOWTIME_ACTIVE = REGISTRY.register("classic_chica_showtime_active", () -> new ClassicChicaShowtimeActiveBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEAR_SHOWTIME = REGISTRY.register("freddy_fazbear_showtime", () -> new FreddyFazbearShowtimeBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEAR_SHOWTIME_ACTIVE = REGISTRY.register("freddy_fazbear_showtime_active", () -> new FreddyFazbearShowtimeActiveBlock());
	public static final RegistryObject<Block> BONNIE_BUNNIE_SHOWTIME = REGISTRY.register("bonnie_bunnie_showtime", () -> new BonnieBunnieShowtimeBlock());
	public static final RegistryObject<Block> BONNIE_BUNNIE_SHOWTIME_ACTIVE = REGISTRY.register("bonnie_bunnie_showtime_active", () -> new BonnieBunnieShowtimeActiveBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_BUNNIE_SHOWTIME = REGISTRY.register("spring_bonnie_bunnie_showtime", () -> new SpringBonnieBunnieShowtimeBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_BUNNIE_SHOWTIME_ACTIVE = REGISTRY.register("spring_bonnie_bunnie_showtime_active", () -> new SpringBonnieBunnieShowtimeActiveBlock());
	public static final RegistryObject<Block> YELLOW_BEAR_SHOWTIME = REGISTRY.register("yellow_bear_showtime", () -> new GoldenFreddyShowtimeBlock());
	public static final RegistryObject<Block> YELLOW_BEAR_SHOWTIME_ACTIVE = REGISTRY.register("yellow_bear_showtime_active", () -> new GoldenFreddyShowtimeActiveBlock());
	public static final RegistryObject<Block> FOXY_PIRATE_SHOWTIME = REGISTRY.register("foxy_pirate_showtime", () -> new FoxyPirateShowtimeBlock());
	public static final RegistryObject<Block> FOXY_PIRATE_SHOWTIME_ACTIVE = REGISTRY.register("foxy_pirate_showtime_active", () -> new FoxyPirateShowtimeActiveBlock());
	public static final RegistryObject<Block> GLITCH_BONNIE_SHOWTIME = REGISTRY.register("glitch_bonnie_showtime", () -> new GlitchtrapShowtimeBlock());
	public static final RegistryObject<Block> GLITCH_BONNIE_SHOWTIME_ACTIVE = REGISTRY.register("glitch_bonnie_showtime_active", () -> new GlitchtrapShowtimeActiveBlock());
	public static final RegistryObject<Block> SHAVEN_BONNIE_SHOWTIME = REGISTRY.register("shaven_bonnie_showtime", () -> new UnBonnieShowtimeBlock());
	public static final RegistryObject<Block> SHAVEN_BONNIE_SHOWTIME_ACTIVE = REGISTRY.register("shaven_bonnie_showtime_active", () -> new UnBonnieShowtimeActiveBlock());
	public static final RegistryObject<Block> FIXED_FOXY_SHOWTIME = REGISTRY.register("fixed_foxy_showtime", () -> new FixedFoxyShowtimeBlock());
	public static final RegistryObject<Block> FIXED_FOXY_SHOWTIME_ACTIVE = REGISTRY.register("fixed_foxy_showtime_active", () -> new FixedFoxyShowtimeActiveBlock());
	public static final RegistryObject<Block> SPRINGTRAP_SHOWTIME = REGISTRY.register("springtrap_showtime", () -> new SpringtrapShowtimeBlock());
	public static final RegistryObject<Block> SPRINGTRAP_SHOWTIME_ACTIVE = REGISTRY.register("springtrap_showtime_active", () -> new SpringtrapShowtimeActiveBlock());
	public static final RegistryObject<Block> A_BONNIE_BUNNIE_SHOWTIME = REGISTRY.register("a_bonnie_bunnie_showtime", () -> new ABonnieBunnieShowtimeBlock());
	public static final RegistryObject<Block> A_BONNIE_BUNNY_ACTIVE = REGISTRY.register("a_bonnie_bunny_active", () -> new ABonnieBunnyActiveBlock());
	public static final RegistryObject<Block> A_BONNIE_SHOWTIME = REGISTRY.register("a_bonnie_showtime", () -> new ABonnieShowtimeBlock());
	public static final RegistryObject<Block> A_BONNIE_ACTIVE = REGISTRY.register("a_bonnie_active", () -> new ABonnieActiveBlock());
	public static final RegistryObject<Block> A_CHICA_SHOWTIME = REGISTRY.register("a_chica_showtime", () -> new AChicaShowtimeBlock());
	public static final RegistryObject<Block> A_CHICA_ACTIVE = REGISTRY.register("a_chica_active", () -> new AChicaActiveBlock());
	public static final RegistryObject<Block> A_CHICA_CHICKEN_SHOWTIME = REGISTRY.register("a_chica_chicken_showtime", () -> new AChicaChickenShowtimeBlock());
	public static final RegistryObject<Block> A_CHICA_CHICKEN_ACTIVE = REGISTRY.register("a_chica_chicken_active", () -> new AChicaChickenActiveBlock());
	public static final RegistryObject<Block> A_FIXED_FOXY_SHOWTIME = REGISTRY.register("a_fixed_foxy_showtime", () -> new AFixedFoxyShowtimeBlock());
	public static final RegistryObject<Block> A_FIXED_FOXY_ACTIVE = REGISTRY.register("a_fixed_foxy_active", () -> new AFixedFoxyActiveBlock());
	public static final RegistryObject<Block> A_SHAVEN_BONNIE_SHOWTIME = REGISTRY.register("a_shaven_bonnie_showtime", () -> new AShavenBonnieShowtimeBlock());
	public static final RegistryObject<Block> A_SHAVEN_BONNIE_ACTIVE = REGISTRY.register("a_shaven_bonnie_active", () -> new AShavenBonnieActiveBlock());
	public static final RegistryObject<Block> A_SPRING_BONNIE_BUNNIE_SHOWTIME = REGISTRY.register("a_spring_bonnie_bunnie_showtime", () -> new ASpringBonnieBunnieShowtimeBlock());
	public static final RegistryObject<Block> A_SPRING_BONNIE_BUNNIE_ACTIVE = REGISTRY.register("a_spring_bonnie_bunnie_active", () -> new ASpringBonnieBunnieActiveBlock());
	public static final RegistryObject<Block> A_FOXY_PIRATE_SHOWTIME = REGISTRY.register("a_foxy_pirate_showtime", () -> new AFoxyPirateShowtimeBlock());
	public static final RegistryObject<Block> A_FOXY_PIRATE_ACTIVE = REGISTRY.register("a_foxy_pirate_active", () -> new AFoxyPirateActiveBlock());
	public static final RegistryObject<Block> A_FREDBEAR_SHOWTIME = REGISTRY.register("a_fredbear_showtime", () -> new AFredbearShowtimeBlock());
	public static final RegistryObject<Block> A_FREDBEAR_ACTIVE = REGISTRY.register("a_fredbear_active", () -> new AFredbearActiveBlock());
	public static final RegistryObject<Block> A_FREDDY_FAZBEAR_SHOWTIME = REGISTRY.register("a_freddy_fazbear_showtime", () -> new AFreddyFazbearShowtimeBlock());
	public static final RegistryObject<Block> A_FREDDY_FAZBEAR_ACTIVE = REGISTRY.register("a_freddy_fazbear_active", () -> new AFreddyFazbearActiveBlock());
	public static final RegistryObject<Block> A_FREDDY_SHOWTIME = REGISTRY.register("a_freddy_showtime", () -> new AFreddyShowtimeBlock());
	public static final RegistryObject<Block> A_FREDDY_ACTIVE = REGISTRY.register("a_freddy_active", () -> new AFreddyActiveBlock());
	public static final RegistryObject<Block> A_SPRING_BONNIE_SHOWTIME = REGISTRY.register("a_spring_bonnie_showtime", () -> new ASpringBonnieShowtimeBlock());
	public static final RegistryObject<Block> A_SPRING_BONNIE_ACTIVE = REGISTRY.register("a_spring_bonnie_active", () -> new ASpringBonnieActiveBlock());
	public static final RegistryObject<Block> A_GLTICH_BONNIE_SHOWTIME = REGISTRY.register("a_gltich_bonnie_showtime", () -> new AGltichBonnieShowtimeBlock());
	public static final RegistryObject<Block> A_GLITCH_BONNIE_ACTIVE = REGISTRY.register("a_glitch_bonnie_active", () -> new AGlitchBonnieActiveBlock());
	public static final RegistryObject<Block> A_SPRINGTRAP_SHOWTIME = REGISTRY.register("a_springtrap_showtime", () -> new ASpringtrapShowtimeBlock());
	public static final RegistryObject<Block> A_SPRINGTRAP_ACTIVE = REGISTRY.register("a_springtrap_active", () -> new ASpringtrapActiveBlock());
	public static final RegistryObject<Block> A_TOY_BONNIE_SHOWTIME = REGISTRY.register("a_toy_bonnie_showtime", () -> new AToyBonnieShowtimeBlock());
	public static final RegistryObject<Block> A_TOY_BONNIE_ACTIVE = REGISTRY.register("a_toy_bonnie_active", () -> new AToyBonnieActiveBlock());
	public static final RegistryObject<Block> A_TOY_CHICA_SHOWTIME = REGISTRY.register("a_toy_chica_showtime", () -> new AToyChicaShowtimeBlock());
	public static final RegistryObject<Block> A_TOY_CHICA_ACTIVE = REGISTRY.register("a_toy_chica_active", () -> new AToyChicaActiveBlock());
	public static final RegistryObject<Block> A_TOY_FOXY_SHOWTIME = REGISTRY.register("a_toy_foxy_showtime", () -> new AToyFoxyShowtimeBlock());
	public static final RegistryObject<Block> A_TOY_FOXY_ACTIVE = REGISTRY.register("a_toy_foxy_active", () -> new AToyFoxyActiveBlock());
	public static final RegistryObject<Block> A_TOY_FREDDY_SHOWTIME = REGISTRY.register("a_toy_freddy_showtime", () -> new AToyFreddyShowtimeBlock());
	public static final RegistryObject<Block> A_TOY_FREDDY_ACTIVE = REGISTRY.register("a_toy_freddy_active", () -> new AToyFreddyActiveBlock());
	public static final RegistryObject<Block> A_YELLOW_BEAR_SHOWTIME = REGISTRY.register("a_yellow_bear_showtime", () -> new AYellowBearShowtimeBlock());
	public static final RegistryObject<Block> A_YELLOW_BEAR_ACTIVE = REGISTRY.register("a_yellow_bear_active", () -> new AYellowBearActiveBlock());
	public static final RegistryObject<Block> A_FOXY_SHOWTIME = REGISTRY.register("a_foxy_showtime", () -> new AFoxyShowtimeBlock());
	public static final RegistryObject<Block> A_FOXY_ACTIVE = REGISTRY.register("a_foxy_active", () -> new AFoxyActiveBlock());
	public static final RegistryObject<Block> EMPTYBOX = REGISTRY.register("emptybox", () -> new EmptyboxBlock());
	public static final RegistryObject<Block> ENDO_02_HEAD = REGISTRY.register("endo_02_head", () -> new Endo02HeadBlock());
	public static final RegistryObject<Block> ENDO_02_TORSO = REGISTRY.register("endo_02_torso", () -> new Endo02TorsoBlock());
	public static final RegistryObject<Block> ENDO_02_LEFT_LEG = REGISTRY.register("endo_02_left_leg", () -> new Endo02LeftLegBlock());
	public static final RegistryObject<Block> ENDO_02_RIGHT_LEG = REGISTRY.register("endo_02_right_leg", () -> new Endo02RightLegBlock());
	public static final RegistryObject<Block> ENDO_02_LEFT_ARM = REGISTRY.register("endo_02_left_arm", () -> new Endo02LeftArmBlock());
	public static final RegistryObject<Block> ENDO_02_RIGHT_ARM = REGISTRY.register("endo_02_right_arm", () -> new Endo02RightArmBlock());
	public static final RegistryObject<Block> OFFSET_FREDDY_SHOWTIME = REGISTRY.register("offset_freddy_showtime", () -> new OffsetFreddyShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_FREDDY_ACTIVE = REGISTRY.register("offset_freddy_active", () -> new OffsetFreddyActiveBlock());
	public static final RegistryObject<Block> BONNIE_BUNNIE_TORSO = REGISTRY.register("bonnie_bunnie_torso", () -> new BonnieBunnieTorsoBlock());
	public static final RegistryObject<Block> BONNIE_BUNNIE_LEFT_ARM = REGISTRY.register("bonnie_bunnie_left_arm", () -> new BonnieBunnieLeftArmBlock());
	public static final RegistryObject<Block> BONNIE_BUNNIE_RIGHT_ARM = REGISTRY.register("bonnie_bunnie_right_arm", () -> new BonnieBunnieRightArmBlock());
	public static final RegistryObject<Block> BONNIE_BUNNIE_HEAD = REGISTRY.register("bonnie_bunnie_head", () -> new BonnieBunnieHeadBlock());
	public static final RegistryObject<Block> BONNIE_BUNNIE_RIGHT_LEG = REGISTRY.register("bonnie_bunnie_right_leg", () -> new BonnieBunnieRightLegBlock());
	public static final RegistryObject<Block> BONNIE_BUNNIE_LEFT_LEG = REGISTRY.register("bonnie_bunnie_left_leg", () -> new BonnieBunnieLeftLegBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_BUNNIE_TORSO = REGISTRY.register("spring_bonnie_bunnie_torso", () -> new SpringBonnieBunnieTorsoBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_BUNNIE_LEFT_ARM = REGISTRY.register("spring_bonnie_bunnie_left_arm", () -> new SpringBonnieBunnieLeftArmBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_BUNNIE_RIGHT_ARM = REGISTRY.register("spring_bonnie_bunnie_right_arm", () -> new SpringBonnieBunnieRightArmBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_BUNNIE_HEAD = REGISTRY.register("spring_bonnie_bunnie_head", () -> new SpringBonnieBunnieHeadBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_BUNNIE_RIGHT_LEG = REGISTRY.register("spring_bonnie_bunnie_right_leg", () -> new SpringBonnieBunnieRightLegBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_BUNNIE_LEFT_LEG = REGISTRY.register("spring_bonnie_bunnie_left_leg", () -> new SpringBonnieBunnieLeftLegBlock());
	public static final RegistryObject<Block> ENDO_02_FOXY_HEAD = REGISTRY.register("endo_02_foxy_head", () -> new Endo02FoxyHeadBlock());
	public static final RegistryObject<Block> ENOD_02_BONNIE_HEAD = REGISTRY.register("enod_02_bonnie_head", () -> new Enod02BonnieHeadBlock());
	public static final RegistryObject<Block> ENDO_02_CHICA_HEAD = REGISTRY.register("endo_02_chica_head", () -> new Endo02ChicaHeadBlock());
	public static final RegistryObject<Block> FRED_BEAR_TORSO = REGISTRY.register("fred_bear_torso", () -> new FredBearTorsoBlock());
	public static final RegistryObject<Block> FRED_BEAR_LEFT_ARM = REGISTRY.register("fred_bear_left_arm", () -> new FredBearLeftArmBlock());
	public static final RegistryObject<Block> FRED_BEAR_RIGHT_ARM = REGISTRY.register("fred_bear_right_arm", () -> new FredBearRightArmBlock());
	public static final RegistryObject<Block> FRED_BEAR_HEAD = REGISTRY.register("fred_bear_head", () -> new FredBearHeadBlock());
	public static final RegistryObject<Block> FRED_BEAR_RIGHT_LEG = REGISTRY.register("fred_bear_right_leg", () -> new FredBearRightLegBlock());
	public static final RegistryObject<Block> FRED_BEAR_LEFT_LEG = REGISTRY.register("fred_bear_left_leg", () -> new FredBearLeftLegBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_TORSO = REGISTRY.register("spring_bonnie_torso", () -> new SpringBonnieTorsoBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_LEFT_ARM = REGISTRY.register("spring_bonnie_left_arm", () -> new SpringBonnieLeftArmBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_RIGHT_ARM = REGISTRY.register("spring_bonnie_right_arm", () -> new SpringBonnieRightArmBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_HEAD = REGISTRY.register("spring_bonnie_head", () -> new SpringBonnieHeadBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_RIGHT_LEG = REGISTRY.register("spring_bonnie_right_leg", () -> new SpringBonnieRightLegBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_LEFT_L_EG = REGISTRY.register("spring_bonnie_left_l_eg", () -> new SpringBonnieLeftLEgBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEAR_TORSO = REGISTRY.register("freddy_fazbear_torso", () -> new FreddyFazbearTorsoBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEAR_LEFT_ARM = REGISTRY.register("freddy_fazbear_left_arm", () -> new FreddyFazbearLeftArmBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEAR_RIGHT_ARM = REGISTRY.register("freddy_fazbear_right_arm", () -> new FreddyFazbearRightArmBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEARHEAD = REGISTRY.register("freddy_fazbearhead", () -> new FreddyFazbearheadBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEAR_RIGHT_LEG = REGISTRY.register("freddy_fazbear_right_leg", () -> new FreddyFazbearRightLegBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEAR_LEFT_LEG = REGISTRY.register("freddy_fazbear_left_leg", () -> new FreddyFazbeareftLegBlock());
	public static final RegistryObject<Block> YELLOW_BEAR_TORSO = REGISTRY.register("yellow_bear_torso", () -> new YellowBearTorsoBlock());
	public static final RegistryObject<Block> YELLOW_BEAR_LEFT_ARM = REGISTRY.register("yellow_bear_left_arm", () -> new YellowBearLeftArmBlock());
	public static final RegistryObject<Block> YELLOW_BEAR_RIGHT_ARM = REGISTRY.register("yellow_bear_right_arm", () -> new YellowBearRightArmBlock());
	public static final RegistryObject<Block> YELLOW_BEAR_HEAD = REGISTRY.register("yellow_bear_head", () -> new YellowBearHeadBlock());
	public static final RegistryObject<Block> YELLOW_BEAR_RIGHT_LEG = REGISTRY.register("yellow_bear_right_leg", () -> new YellowBearRightLegBlock());
	public static final RegistryObject<Block> YELLOW_BEAR_LEFT_LEG = REGISTRY.register("yellow_bear_left_leg", () -> new YellowBearLeftLegBlock());
	public static final RegistryObject<Block> GLITCH_BONNIE_TORSO = REGISTRY.register("glitch_bonnie_torso", () -> new GlitchBonnieTorsoBlock());
	public static final RegistryObject<Block> GLITCH_BONNIE_HEAD = REGISTRY.register("glitch_bonnie_head", () -> new GlitchBonnieHeadBlock());
	public static final RegistryObject<Block> ENDO_01_TORSO = REGISTRY.register("endo_01_torso", () -> new Endo01TorsoBlock());
	public static final RegistryObject<Block> ENDO_01_LEFT_ARM = REGISTRY.register("endo_01_left_arm", () -> new Endo01LeftArmBlock());
	public static final RegistryObject<Block> ENDO_01_RIGHT_ARM = REGISTRY.register("endo_01_right_arm", () -> new Endo01RightArmBlock());
	public static final RegistryObject<Block> ENDO_01_HEAD = REGISTRY.register("endo_01_head", () -> new Endo01HeadBlock());
	public static final RegistryObject<Block> ENDO_01_RIGHT_LEG = REGISTRY.register("endo_01_right_leg", () -> new Endo01RightLegBlock());
	public static final RegistryObject<Block> ENDO_01_LEFT_LEG = REGISTRY.register("endo_01_left_leg", () -> new Endo01LeftLegBlock());
	public static final RegistryObject<Block> FREDDY_BOX_SPIN = REGISTRY.register("freddy_box_spin", () -> new FreddyBoxSpinBlock());
	public static final RegistryObject<Block> FREDDY_BOX_ACTIVE = REGISTRY.register("freddy_box_active", () -> new FreddyBoxActiveBlock());
	public static final RegistryObject<Block> CHICA_CHICKEN_TORSO = REGISTRY.register("chica_chicken_torso", () -> new ChicaChickenTorsoBlock());
	public static final RegistryObject<Block> CHICA_CHICKEN_LEFT_ARM = REGISTRY.register("chica_chicken_left_arm", () -> new ChicaChickenLeftArmBlock());
	public static final RegistryObject<Block> CHICA_CHICKEN_RIGHT_ARM = REGISTRY.register("chica_chicken_right_arm", () -> new ChicaChickenRightArmBlock());
	public static final RegistryObject<Block> CHICA_CHICKEN_HEAD = REGISTRY.register("chica_chicken_head", () -> new ChicaChickenHeadBlock());
	public static final RegistryObject<Block> CHICA_CHICKEN_RIGHT_LEG = REGISTRY.register("chica_chicken_right_leg", () -> new ChicaChickenRightLegBlock());
	public static final RegistryObject<Block> CHICA_CHICKEN_LEFT_LEG = REGISTRY.register("chica_chicken_left_leg", () -> new ChicaChickenLeftLegBlock());
	public static final RegistryObject<Block> PUPPET_BOX_GIFT = REGISTRY.register("puppet_box_gift", () -> new PuppetBoxGiftBlock());
	public static final RegistryObject<Block> PUPPET_BOX_SLUMPED = REGISTRY.register("puppet_box_slumped", () -> new PuppetBoxSlumpedBlock());
	public static final RegistryObject<Block> PUPPET_BOX_WINDING = REGISTRY.register("puppet_box_winding", () -> new PuppetBoxWindingBlock());
	public static final RegistryObject<Block> PUPPET_BOX_JUMPSCARE = REGISTRY.register("puppet_box_jumpscare", () -> new PuppetBoxJumpscareBlock());
	public static final RegistryObject<Block> FOXY_PIRATE_TORSO = REGISTRY.register("foxy_pirate_torso", () -> new FoxyPirateTorsoBlock());
	public static final RegistryObject<Block> FOXY_PIRATE_LEFT_ARM = REGISTRY.register("foxy_pirate_left_arm", () -> new FoxyPirateLeftArmBlock());
	public static final RegistryObject<Block> FOXY_PIRATE_RIGHT_ARM = REGISTRY.register("foxy_pirate_right_arm", () -> new FoxyPirateRightArmBlock());
	public static final RegistryObject<Block> FOXY_PIRATE_HEAD = REGISTRY.register("foxy_pirate_head", () -> new FoxyPirateHeadBlock());
	public static final RegistryObject<Block> FOXY_PIRATE_RIGHT_LEG = REGISTRY.register("foxy_pirate_right_leg", () -> new FoxyPirateRightLegBlock());
	public static final RegistryObject<Block> FOXY_PIRATE_LEFT_LEG = REGISTRY.register("foxy_pirate_left_leg", () -> new FoxyPirateLeftLegBlock());
	public static final RegistryObject<Block> BROKEN_FOXY_PIRATE_TORSO = REGISTRY.register("broken_foxy_pirate_torso", () -> new BrokenFoxyPirateTorsoBlock());
	public static final RegistryObject<Block> BROKEN_FOXY_PIRATE_LEFT_ARM = REGISTRY.register("broken_foxy_pirate_left_arm", () -> new BrokenFoxyPirateLeftArmBlock());
	public static final RegistryObject<Block> BROKEN_FOXY_PIRATE_RIGHT_ARM = REGISTRY.register("broken_foxy_pirate_right_arm", () -> new BrokenFoxyPirateRightArmBlock());
	public static final RegistryObject<Block> BROKEN_FOXY_PIRATE_HEAD = REGISTRY.register("broken_foxy_pirate_head", () -> new BrokenFoxyPirateHeadBlock());
	public static final RegistryObject<Block> BROKEN_FOXY_PIRATE_RIGHT_LEG = REGISTRY.register("broken_foxy_pirate_right_leg", () -> new BrokenFoxyPirateRightLegBlock());
	public static final RegistryObject<Block> BROKEN_FOXY_PIRATE_LEFT_LEG = REGISTRY.register("broken_foxy_pirate_left_leg", () -> new BrokenFoxyPirateLeftLegBlock());
	public static final RegistryObject<Block> OFFSET_FREDDY_FAZBEAR_SHOWTIME = REGISTRY.register("offset_freddy_fazbear_showtime", () -> new OffsetFreddyFazbearShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_FREDDY_FAZBEAR_ACTIVE = REGISTRY.register("offset_freddy_fazbear_active", () -> new OffsetFreddyFazbearActiveBlock());
	public static final RegistryObject<Block> OFFSET_FRED_BEAR_SHOWTIME = REGISTRY.register("offset_fred_bear_showtime", () -> new OffsetFredBearShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_FRED_BEAR_ACTIVE = REGISTRY.register("offset_fred_bear_active", () -> new OffsetFredBearActiveBlock());
	public static final RegistryObject<Block> OFFSET_TOY_FREDDY_SHOWTIME = REGISTRY.register("offset_toy_freddy_showtime", () -> new OffsetToyFreddyShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_TOY_FREDDY_ACTIVE = REGISTRY.register("offset_toy_freddy_active", () -> new OffsetToyFreddyActiveBlock());
	public static final RegistryObject<Block> OFFSET_SPRING_BONNIE_SHOWTIME = REGISTRY.register("offset_spring_bonnie_showtime", () -> new OffsetSpringBonnieShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_SPRING_BONNIE_ACTIVE = REGISTRY.register("offset_spring_bonnie_active", () -> new OffsetSpringBonnieActiveBlock());
	public static final RegistryObject<Block> OFFSET_FOXY_SHOWTIME = REGISTRY.register("offset_foxy_showtime", () -> new OffsetFoxyShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_FOXY_ACTIVE = REGISTRY.register("offset_foxy_active", () -> new OffsetFoxyActiveBlock());
	public static final RegistryObject<Block> OFFSET_FOXY_PIRATE_SHOWTIME = REGISTRY.register("offset_foxy_pirate_showtime", () -> new OffsetFoxyPirateShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_FOXY_PIRATE_ACTIVE = REGISTRY.register("offset_foxy_pirate_active", () -> new OffsetFoxyPirateActiveBlock());
	public static final RegistryObject<Block> OFFSET_FIXED_FOXY_SHOWTIME = REGISTRY.register("offset_fixed_foxy_showtime", () -> new OffsetFixedFoxyShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_FIXED_FOXY_ACTIVE = REGISTRY.register("offset_fixed_foxy_active", () -> new OffsetFixedFoxyActiveBlock());
	public static final RegistryObject<Block> OFFSET_TOY_FOXY_SHOWTIME = REGISTRY.register("offset_toy_foxy_showtime", () -> new OffsetToyFoxyShowtimeBlock());
	public static final RegistryObject<Block> OFFSET_TOY_FOXY_ACTIVE = REGISTRY.register("offset_toy_foxy_active", () -> new OffsetToyFoxyActiveBlock());
	public static final RegistryObject<Block> GENERATOR = REGISTRY.register("generator", () -> new GeneratorBlock());
	public static final RegistryObject<Block> GENERATOR_1 = REGISTRY.register("generator_1", () -> new Generator1Block());
	public static final RegistryObject<Block> GENERATOR_2 = REGISTRY.register("generator_2", () -> new Generator2Block());
	public static final RegistryObject<Block> GENERATOR_3 = REGISTRY.register("generator_3", () -> new Generator3Block());
	public static final RegistryObject<Block> GENERATOR_4 = REGISTRY.register("generator_4", () -> new Generator4Block());
	public static final RegistryObject<Block> GENERATOR_5 = REGISTRY.register("generator_5", () -> new Generator5Block());
	public static final RegistryObject<Block> GENERATOR_6 = REGISTRY.register("generator_6", () -> new Generator6Block());
	public static final RegistryObject<Block> GENERATOR_7 = REGISTRY.register("generator_7", () -> new Generator7Block());
	public static final RegistryObject<Block> GENERATOR_8 = REGISTRY.register("generator_8", () -> new Generator8Block());
	public static final RegistryObject<Block> CHRISTMAS_FREDDY = REGISTRY.register("christmas_freddy", () -> new ChristmasFreddyBlock());
	public static final RegistryObject<Block> CHRISTMAS_FREDDY_A = REGISTRY.register("christmas_freddy_a", () -> new ChristmasFreddyABlock());
	public static final RegistryObject<Block> CHRISTMAS_BONNIE = REGISTRY.register("christmas_bonnie", () -> new ChristmasBonnieBlock());
	public static final RegistryObject<Block> CHRISTMAS_BONNIE_A = REGISTRY.register("christmas_bonnie_a", () -> new ChristmasBonnieABlock());
	public static final RegistryObject<Block> CHRISTMAS_CHICA = REGISTRY.register("christmas_chica", () -> new ChristmasChicaBlock());
	public static final RegistryObject<Block> CHRISTMAS_CHICA_A = REGISTRY.register("christmas_chica_a", () -> new ChristmasChicaABlock());
	public static final RegistryObject<Block> CHRISTMAS_FOXY = REGISTRY.register("christmas_foxy", () -> new ChristmasFoxyBlock());
	public static final RegistryObject<Block> CHRISTMAS_FOXY_A = REGISTRY.register("christmas_foxy_a", () -> new ChristmasFoxyABlock());
	public static final RegistryObject<Block> ENDO_02_BLOCK = REGISTRY.register("endo_02_block", () -> new Endo02BlockBlock());
	public static final RegistryObject<Block> VASSILIS = REGISTRY.register("vassilis", () -> new VassilisBlock());
	public static final RegistryObject<Block> VASSILIS_A = REGISTRY.register("vassilis_a", () -> new VassilisABlock());
	public static final RegistryObject<Block> VASSTRONIC = REGISTRY.register("vasstronic", () -> new VasstronicBlock());
	public static final RegistryObject<Block> BLLOON_BOY_STATUE = REGISTRY.register("blloon_boy_statue", () -> new BlloonBoyStatueBlock());
	public static final RegistryObject<Block> TOY_CARNIE_SHOWTIME = REGISTRY.register("toy_carnie_showtime", () -> new ToyCarnieShowtimeBlock());
	public static final RegistryObject<Block> TOY_CARNIE_ACTIVE = REGISTRY.register("toy_carnie_active", () -> new ToyCarnieActiveBlock());
	public static final RegistryObject<Block> CAPTAIN_FOXY_STATUE = REGISTRY.register("captain_foxy_statue", () -> new CaptainFoxyStatueBlock());
	public static final RegistryObject<Block> ANGLED_TOY_CARNIE = REGISTRY.register("angled_toy_carnie", () -> new AngledToyCarnieBlock());
	public static final RegistryObject<Block> ANGLED_BLLOON_BOY_STATUE = REGISTRY.register("angled_blloon_boy_statue", () -> new AngledBlloonBoyStatueBlock());
	public static final RegistryObject<Block> PUPPETWALLDECOR = REGISTRY.register("puppetwalldecor", () -> new PuppetwalldecorBlock());
	public static final RegistryObject<Block> BURNT_TOY_FREDDY_JUMPSCARE = REGISTRY.register("burnt_toy_freddy_jumpscare", () -> new BurntToyFreddyJumpscareBlock());
	public static final RegistryObject<Block> BURNT_TOY_BONNIE_JUMPSCARE = REGISTRY.register("burnt_toy_bonnie_jumpscare", () -> new BurntToyBonnieJumpscareBlock());
	public static final RegistryObject<Block> BURNT_TOY_CHICA = REGISTRY.register("burnt_toy_chica", () -> new BurntToyChicaBlock());
}
